---
- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - epel-release
    - ntp

- name: Set NTP Service Fact
  set_fact:
    ntp_service: ntpdate
