---
- name: Include RedHat Vars
  include_vars: RedHat.yml

- name: Install dependencies
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ wordpress_dependencies }}'

- name: Create .my.cnf
  template:
    backup: yes
    dest: ~root/.my.cnf
    src: my.cnf.j2
