---
- name: Copy /etc/default/jenkins
  template:
    src: 'Common/jenkins.j2'
    dest: '/etc/default/jenkins'

- name: Set Jenkins URL
  template:
    src: 'Common/jenkins.model.JenkinsLocationConfiguration.xml.j2'
    dest: '/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml'

- name: Install Python BCrypt
  pip:
    name: bcrypt
    state: present

- name: Generate Jenkins Password
  shell: python -c "import bcrypt; print(bcrypt.hashpw('{{ jenkins_admin_pass }}', bcrypt.gensalt(10, prefix=b'2a')))"
  register: jenkins_password_crypt

- name: Generate Jenkins API key
  shell: python -c "import os; import hashlib; print(hashlib.sha256(os.urandom(128)).hexdigest())"
  register: jenkins_api_key

- name: Ensure Jenkins Admin User Directory exists
  file:
    path: '/var/lib/jenkins/users/admin'
    state: directory
    owner: jenkins
    group: jenkins

- name: Configure Jenkins Admin User
  template:
    src: 'Common/user_config.xml.j2'
    dest: '/var/lib/jenkins/users/admin/config.xml'

- name: Enable Jenkins CLI
  template:
    src: 'Common/jenkins_config.xml.j2'
    dest: '/var/lib/jenkins/config.xml'

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Enable Jenkins
  service:
    name: jenkins
    enabled: yes

- name: Wait for Jenkins to initialize
  wait_for:
    timeout: 30

- name: Install Jenkins Plugins
  shell:
    'java -jar {{ jenkins_cli }} -s {{ jenkins_url }} install-plugin http://updates.jenkins-ci.org/latest/{{ item }}.hpi --username admin --password {{ jenkins_admin_pass }}'
  with_items: '{{ jenkins_plugins }}'

- name: Configure Swarm User
  shell: |
    echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("swarm", "{{ swarm_password }}")' | java -jar {{ jenkins_cli }} -s {{ jenkins_url }} groovy = --username admin --password {{ jenkins_admin_pass }}

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to initialize
  wait_for:
    timeout: 60
