---
- name: Install IUS repository - CentOS
  yum:
    name: 'https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm'
  when: ansible_distribution == 'CentOS'

- name: Install IUS repository
  yum:
    name: 'https://rhel{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm'
  when: ansible_distribution == 'RedHat'
