---
# RAX dedicated linux servers use the IUS channel via RHN
# Have not yet figured this out...
#- name: IUS channel via RHN is present
#  rhn_channel: state=present name=rackspace-managed-centos6-x86_64-ius
#  when: ansible_os_family == "RedHat" and ansible_form_factor == "Rack Mount Chassis"

# Install IUS via templates on cloud servers
- name: check if EL ius repo is present...
  shell: yum repolist | grep -i ius
  register: ius_check
  ignore_errors: yes
  when: ansible_os_family == "RedHat" and ansible_form_factor != "Rack Mount Chassis"

- name: ius.repo is installed
  template: 
    src=etc/yum.repos.d/ius.repo.j2
    dest=/etc/yum.repos.d/ius.repo
    backup=yes
  when: ansible_form_factor != "Rack Mount Chassis" and ius_check.rc == 1 and ansible_os_family == "RedHat"

- name: ius gpg key is present
  copy: 
    src=etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
    dest=/etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
    backup=yes
  when: ansible_form_factor != "Rack Mount Chassis" and ius_check.rc == 1 and ansible_os_family == "RedHat"
